name: Publish Docker image

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
    packages: write

env:
  REGISTRY_IMAGE: ghcr.io/tsukina-7mochi/discord-my-server-bot


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t prod --tag ${{ env.REGISTRY_IMAGE }}:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ env.REGISTRY_IMAGE }}:latest
